plugin.plugin_configuration.adapter_type.local:*:
  type: mapping
  label: 'Flysystem Local Adapter Setttings'
  mapping:
    adapter_type:
      type: string
      label:  'Flysystem Adapter Type'
    schema:
      type: string
      label: 'Schema to identify file designations using this adapter instance (public, private, tmp, etc.)'
    files_location:
      type: string
      label: 'Path to file storage (relative to Drupal root)'
    visibility:
      file:
        public:
          type: string
          label: 'Public file permissions'
        private:
          type: string
          label: 'Private file permissions'
      directory:
        public:
          type: string
          label: 'Public directory permissions'
        private:
          type: string
          label: 'Private directory permissions'
      default_for_directories:
        type:  string
        label: 'Default visibility for directories'
